name: Build using conan
on:
  pull_request:
  push:
  release:
    types: published
jobs:
  build-cmake:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        crypto: [openssl, wolfssl, None]
        event: [libuv, kqueue, epoll, gcd]
        exclude:
          - os: windows-latest
            event: [kqueue, epoll, gcd]
          - os: ubuntu-latest
            event: gcd
          - os: ubuntu-latest
            event: kqueue
          - os: macos-latest
            event: epoll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Install conan"
        run: |
          python -m pip install conan
          conan user
      - name: 'Set up directories'
        run: mkdir build && cd build
      - name: "conan install (download/build dependencies)"
        run: |
          conan install ${{ github.workspace }} -o crypto=${{ matrix.crypto}} -o event=${{ matrix.event }} --build missing
      - name: "conan build (build uSockets)"
        run: |
          conan build ${{ github.workspace }}
